#!/usr/bin/env node
'use strict';

/**
 * Build the Chrome extension content script (rrweb-recorder.js).
 *
 * Produces a single IIFE file that:
 *   1. Loads rrweb (IIFE, global `rrweb`)
 *   2. Loads rrweb console plugin (IIFE, global `rrwebConsolePlugin`)
 *   3. Runs the recorder wrapper (main frame: full recording + network capture;
 *      iframe: no-op emit, rrweb PostMessages events to parent)
 *
 * Content scripts are authored in TypeScript (src/*.ts) and compiled to
 * browser IIFEs via esbuild.transform(). Same pattern as scripts/bundle-cf-scripts.ts.
 */

import { build, transform } from 'esbuild';
import fs from 'fs/promises';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const rootDir = join(__dirname, '..', '..');
const outDir = join(__dirname);
const srcDir = join(__dirname, 'src');

const rrwebOutfile = join(rootDir, 'build', 'ext-rrweb-bundle.js');
const consoleOutfile = join(rootDir, 'build', 'ext-rrweb-console-plugin-bundle.js');

/**
 * Compile a TypeScript source file to a self-executing IIFE string.
 */
async function compileContentScript(filename) {
  const source = await fs.readFile(join(srcDir, filename), 'utf-8');
  const result = await transform(source, {
    loader: 'ts',
    target: ['chrome90'],
  });
  return `(function(){${result.code}})()`;
}

(async () => {
  await fs.mkdir(join(rootDir, 'build'), { recursive: true });

  // 1. Bundle @divmode/rrweb as IIFE
  await build({
    entryPoints: [join(rootDir, 'node_modules/@divmode/rrweb/dist/rrweb.js')],
    bundle: true,
    format: 'iife',
    globalName: 'rrweb',
    outfile: rrwebOutfile,
    minify: true,
    platform: 'browser',
    target: ['chrome90'],
  });

  // 2. Bundle @divmode/rrweb-plugin-console-record as IIFE
  await build({
    entryPoints: [join(rootDir, 'node_modules/@divmode/rrweb-plugin-console-record/dist/rrweb-plugin-console-record.js')],
    bundle: true,
    format: 'iife',
    globalName: 'rrwebConsolePlugin',
    outfile: consoleOutfile,
    minify: true,
    platform: 'browser',
    target: ['chrome90'],
  });

  const rrwebScript = await fs.readFile(rrwebOutfile, 'utf-8');
  const consoleScript = await fs.readFile(consoleOutfile, 'utf-8');

  // 3. Compile TypeScript content scripts to IIFEs
  const [recorderWrapper, networkCapture] = await Promise.all([
    compileContentScript('recorder.ts'),
    compileContentScript('network-capture.ts'),
  ]);

  // 4. Concatenate: rrweb IIFE + console plugin IIFE + recorder wrapper + network capture
  const finalScript = [
    '// Auto-generated by extensions/replay/build.js — DO NOT EDIT',
    '// Bundled @divmode/rrweb + console plugin + recorder + network capture',
    rrwebScript,
    consoleScript,
    recorderWrapper,
    networkCapture,
  ].join('\n');

  await fs.writeFile(join(outDir, 'rrweb-recorder.js'), finalScript);
  const sizeKB = Math.round(finalScript.length / 1024);
  console.log(`Built extensions/replay/rrweb-recorder.js (${sizeKB}KB)`);
})();
