#!/usr/bin/env bun
/* eslint-disable no-undef */

/**
 * Bundles CF-related browser scripts (TypeScript → minified IIFE strings).
 * Separate from rrweb bundling — only CF solver scripts live here.
 *
 * Produces TWO outputs from find-turnstile-target.ts:
 *
 *   FIND_TURNSTILE_TARGET_JS — IIFE returning JSON string (for Runtime.evaluate fallback)
 *   TURNSTILE_TARGET_OBSERVER_JS — self-executing script with MutationObserver + binding
 *
 * Usage: bun scripts/bundle-cf-scripts.ts
 */

import { transform } from 'esbuild';
import fs from 'fs/promises';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const rootDir = join(__dirname, '..');
const generatedDir = join(rootDir, 'src', 'generated');
const generatedFile = join(generatedDir, 'cf-scripts.ts');

const OBSERVER_MARKER = '// ── Observer wrapper';

async function loadSource(): Promise<string> {
  return fs.readFile(
    join(rootDir, 'src', 'shared', 'find-turnstile-target.ts'),
    'utf-8',
  );
}

/**
 * IIFE variant for Runtime.evaluate fallback.
 * Strips the observer block (everything after the marker comment) and wraps
 * findTurnstileTarget() in JSON.stringify((function(){ ... return ... })()).
 */
async function bundleTurnstileTargetIIFE(source: string): Promise<string> {
  // Strip observer block — only keep the cascade functions
  const markerIdx = source.indexOf(OBSERVER_MARKER);
  const cascadeOnly = markerIdx !== -1 ? source.substring(0, markerIdx) : source;

  // Also strip the `declare function __turnstileTargetBinding` line (not needed in IIFE)
  const cleaned = cascadeOnly.replace(/^declare function __turnstileTargetBinding.*$/m, '');

  const result = await transform(cleaned, {
    loader: 'ts',
    minify: true,
    target: ['chrome90'],
  });

  return `JSON.stringify((function(){${result.code}return findTurnstileTarget();})())`;
}

/**
 * Observer variant for Page.addScriptToEvaluateOnNewDocument.
 * Full source including MutationObserver + __turnstileTargetBinding call.
 * Wrapped in self-executing IIFE (fire-and-forget, no return value).
 */
async function bundleTurnstileTargetObserver(source: string): Promise<string> {
  // Strip the `declare function` line — it's a TS-only declaration
  const cleaned = source.replace(/^declare function __turnstileTargetBinding.*$/m, '');

  const result = await transform(cleaned, {
    loader: 'ts',
    minify: true,
    target: ['chrome90'],
  });

  return `(function(){${result.code}})()`;
}

(async () => {
  await fs.mkdir(generatedDir, { recursive: true });

  const source = await loadSource();
  const [turnstileTargetJs, turnstileTargetObserverJs] = await Promise.all([
    bundleTurnstileTargetIIFE(source),
    bundleTurnstileTargetObserver(source),
  ]);

  const tsContent = `// Auto-generated by scripts/bundle-cf-scripts.ts - DO NOT EDIT
// Bundled from src/shared/find-turnstile-target.ts

// IIFE returning JSON string — used by Runtime.evaluate fallback
export const FIND_TURNSTILE_TARGET_JS = ${JSON.stringify(turnstileTargetJs)};

// Self-executing observer script — injected via Page.addScriptToEvaluateOnNewDocument
// Sets up MutationObserver + immediate check, calls __turnstileTargetBinding on match
export const TURNSTILE_TARGET_OBSERVER_JS = ${JSON.stringify(turnstileTargetObserverJs)};
`;

  await fs.writeFile(generatedFile, tsContent);
  console.log('Generated src/generated/cf-scripts.ts (FIND_TURNSTILE_TARGET_JS + TURNSTILE_TARGET_OBSERVER_JS)');
})();
