#!/usr/bin/env bun
/* eslint-disable no-undef */

/**
 * Bundles CF-related browser scripts (TypeScript → minified IIFE strings).
 * Separate from rrweb bundling — only CF solver scripts live here.
 *
 * Usage: bun scripts/bundle-cf-scripts.ts
 */

import { transform } from 'esbuild';
import fs from 'fs/promises';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const rootDir = join(__dirname, '..');
const generatedDir = join(rootDir, 'src', 'generated');
const generatedFile = join(generatedDir, 'cf-scripts.ts');

async function bundleTurnstileTarget(): Promise<string> {
  const source = await fs.readFile(
    join(rootDir, 'src', 'shared', 'find-turnstile-target.ts'),
    'utf-8',
  );

  // Strip TypeScript types + minify — no bundling needed (no imports)
  const result = await transform(source, {
    loader: 'ts',
    minify: true,
    target: ['chrome90'],
  });

  // Wrap in IIFE that returns JSON string for Runtime.evaluate
  // Pattern: JSON.stringify((function() { ...code... return findTurnstileTarget(); })())
  return `JSON.stringify((function(){${result.code}return findTurnstileTarget();})())`;
}

(async () => {
  await fs.mkdir(generatedDir, { recursive: true });

  const turnstileTargetJs = await bundleTurnstileTarget();

  const tsContent = `// Auto-generated by scripts/bundle-cf-scripts.ts - DO NOT EDIT
// Bundled from src/shared/find-turnstile-target.ts for browser injection via Runtime.evaluate

export const FIND_TURNSTILE_TARGET_JS = ${JSON.stringify(turnstileTargetJs)};
`;

  await fs.writeFile(generatedFile, tsContent);
  console.log('Generated src/generated/cf-scripts.ts');
})();
