// Code generated by OTel Weaver — DO NOT EDIT.
// Run `just generate-otel` to regenerate.
/** Active libuv handles breakdown by type */
export const METRIC_BROWSERLESS_ACTIVE_HANDLES_BY_TYPE = {
  name: "browserless_active_handles_by_type",
  otel_name: "browserless.active.handles.by.type",
  unit: "{handle}",
  instrument: "gauge",
} as const;
/** Service availability boolean gauge (1=yes, 0=no) */
export const METRIC_BROWSERLESS_AVAILABLE = {
  name: "browserless_available_ratio",
  otel_name: "browserless.available",
  unit: "1",
  instrument: "gauge",
} as const;
/** Full CF click pipeline duration (phase 1 through phase 4) */
export const METRIC_BROWSERLESS_CF_CLICK_PIPELINE_DURATION = {
  name: "browserless_cf_click_pipeline_duration_seconds",
  otel_name: "browserless.cf.click.pipeline.duration",
  unit: "s",
  instrument: "histogram",
} as const;
/** Click attempt result counter */
export const METRIC_BROWSERLESS_CF_CLICK_RESULT = {
  name: "browserless_cf_click_result_total",
  otel_name: "browserless.cf.click.result",
  unit: "{click}",
  instrument: "counter",
} as const;
/** Click-to-resolve duration histogram */
export const METRIC_BROWSERLESS_CF_CLICK_TO_RESOLVE = {
  name: "browserless_cf_click_to_resolve_seconds",
  otel_name: "browserless.cf.click.to.resolve",
  unit: "s",
  instrument: "histogram",
} as const;
/** CF challenge detections registered */
export const METRIC_BROWSERLESS_CF_DETECTION = {
  name: "browserless_cf_detection_total",
  otel_name: "browserless.cf.detection",
  unit: "{detection}",
  instrument: "counter",
} as const;
/** Managed challenge click without navigation counter */
export const METRIC_BROWSERLESS_CF_MANAGED_CLICK_NO_NAV = {
  name: "browserless_cf_managed_click_no_nav_total",
  otel_name: "browserless.cf.managed.click.no.nav",
  unit: "{click}",
  instrument: "counter",
} as const;
/** OOPIF discovery phase histogram */
export const METRIC_BROWSERLESS_CF_PHASE2_DURATION = {
  name: "browserless_cf_phase2_duration_seconds",
  otel_name: "browserless.cf.phase2.duration",
  unit: "s",
  instrument: "histogram",
} as const;
/** Checkbox find phase histogram */
export const METRIC_BROWSERLESS_CF_PHASE3_DURATION = {
  name: "browserless_cf_phase3_duration_seconds",
  otel_name: "browserless.cf.phase3.duration",
  unit: "s",
  instrument: "histogram",
} as const;
/** Click dispatch phase histogram */
export const METRIC_BROWSERLESS_CF_PHASE4_DURATION = {
  name: "browserless_cf_phase4_duration_seconds",
  otel_name: "browserless.cf.phase4.duration",
  unit: "s",
  instrument: "histogram",
} as const;
/** CF resolution timeout counter */
export const METRIC_BROWSERLESS_CF_RESOLUTION_TIMEOUT = {
  name: "browserless_cf_resolution_timeout_total",
  otel_name: "browserless.cf.resolution.timeout",
  unit: "{timeout}",
  instrument: "counter",
} as const;
/** CF challenge resolution counter */
export const METRIC_BROWSERLESS_CF_SOLVE = {
  name: "browserless_cf_solve_total",
  otel_name: "browserless.cf.solve",
  unit: "{solve}",
  instrument: "counter",
} as const;
/** Total solve duration histogram */
export const METRIC_BROWSERLESS_CF_SOLVE_DURATION = {
  name: "browserless_cf_solve_duration_seconds",
  otel_name: "browserless.cf.solve.duration",
  unit: "s",
  instrument: "histogram",
} as const;
/** Chrome main process RSS memory */
export const METRIC_BROWSERLESS_CHROME_MEMORY_RSS = {
  name: "browserless_chrome_memory_rss_bytes",
  otel_name: "browserless.chrome.memory.rss",
  unit: "By",
  instrument: "gauge",
} as const;
/** Chrome renderer process count (zombie detection) */
export const METRIC_BROWSERLESS_CHROME_RENDERER_COUNT = {
  name: "browserless_chrome_renderer_count",
  otel_name: "browserless.chrome.renderer.count",
  unit: "{process}",
  instrument: "gauge",
} as const;
/** Chrome CDP target count (active pages) */
export const METRIC_BROWSERLESS_CHROME_TARGET_COUNT = {
  name: "browserless_chrome_target_count",
  otel_name: "browserless.chrome.target.count",
  unit: "{target}",
  instrument: "gauge",
} as const;
/** Chrome blob worker count (orphan WASM leak detection) */
export const METRIC_BROWSERLESS_CHROME_WORKER_COUNT = {
  name: "browserless_chrome_worker_count",
  otel_name: "browserless.chrome.worker.count",
  unit: "{worker}",
  instrument: "gauge",
} as const;
/** Configured maximum concurrent tabs (for dynamic dashboard thresholds) */
export const METRIC_BROWSERLESS_CONFIG_MAX_CONCURRENT_TABS = {
  name: "browserless_config_max_concurrent_tabs",
  otel_name: "browserless.config.max.concurrent.tabs",
  unit: "{tab}",
  instrument: "gauge",
} as const;
/** CPU usage percent gauge */
export const METRIC_BROWSERLESS_CPU_PERCENT = {
  name: "browserless_cpu_percent_ratio",
  otel_name: "browserless.cpu.percent",
  unit: "1",
  instrument: "gauge",
} as const;
/** Estimated monthly billing units gauge */
export const METRIC_BROWSERLESS_ESTIMATED_MONTHLY_UNITS = {
  name: "browserless_estimated_monthly_units",
  otel_name: "browserless.estimated.monthly.units",
  unit: "{unit}",
  instrument: "gauge",
} as const;
/** Peak concurrent sessions gauge */
export const METRIC_BROWSERLESS_MAX_CONCURRENT_PEAK = {
  name: "browserless_max_concurrent_peak",
  otel_name: "browserless.max.concurrent.peak",
  unit: "{session}",
  instrument: "gauge",
} as const;
/** Max concurrent sessions config gauge */
export const METRIC_BROWSERLESS_MAX_CONCURRENT_SESSIONS = {
  name: "browserless_max_concurrent_sessions",
  otel_name: "browserless.max.concurrent_sessions",
  unit: "{session}",
  instrument: "gauge",
} as const;
/** Max queue size config gauge */
export const METRIC_BROWSERLESS_MAX_QUEUED = {
  name: "browserless_max_queued",
  otel_name: "browserless.max.queued",
  unit: "{session}",
  instrument: "gauge",
} as const;
/** Memory usage percent gauge */
export const METRIC_BROWSERLESS_MEMORY_PERCENT = {
  name: "browserless_memory_percent_ratio",
  otel_name: "browserless.memory.percent",
  unit: "1",
  instrument: "gauge",
} as const;
/** Proxy dropped messages counter */
export const METRIC_BROWSERLESS_PROXY_DROPPED_MESSAGES = {
  name: "browserless_proxy_dropped_messages_total",
  otel_name: "browserless.proxy.dropped.messages",
  unit: "{message}",
  instrument: "counter",
} as const;
/** Replay estimated recording size */
export const METRIC_BROWSERLESS_REPLAY_ESTIMATED = {
  name: "browserless_replay_estimated_bytes",
  otel_name: "browserless.replay.estimated",
  unit: "By",
  instrument: "gauge",
} as const;
/** Replay events counter */
export const METRIC_BROWSERLESS_REPLAY_EVENTS = {
  name: "browserless_replay_events_total",
  otel_name: "browserless.replay.events",
  unit: "{event}",
  instrument: "counter",
} as const;
/** Replay buffer overflow counter */
export const METRIC_BROWSERLESS_REPLAY_OVERFLOWS = {
  name: "browserless_replay_overflows_total",
  otel_name: "browserless.replay.overflows",
  unit: "{overflow}",
  instrument: "counter",
} as const;
/** Replay pending CDP commands gauge */
export const METRIC_BROWSERLESS_REPLAY_PENDING_COMMANDS = {
  name: "browserless_replay_pending_commands",
  otel_name: "browserless.replay.pending.commands",
  unit: "{command}",
  instrument: "gauge",
} as const;
/** Active replay sessions gauge */
export const METRIC_BROWSERLESS_REPLAY_SESSIONS_ACTIVE = {
  name: "browserless_replay_sessions_active",
  otel_name: "browserless.replay.sessions.active",
  unit: "{session}",
  instrument: "gauge",
} as const;
/** Replay WS connections gauge */
export const METRIC_BROWSERLESS_REPLAY_WS_CONNECTIONS = {
  name: "browserless_replay_ws_connections",
  otel_name: "browserless.replay.ws.connections",
  unit: "{connection}",
  instrument: "gauge",
} as const;
/** Session duration histogram */
export const METRIC_BROWSERLESS_SESSION_DURATION = {
  name: "browserless_session_duration_seconds",
  otel_name: "browserless.session.duration",
  unit: "s",
  instrument: "histogram",
} as const;
/** Maximum session time in milliseconds */
export const METRIC_BROWSERLESS_SESSION_TIME_MAX = {
  name: "browserless_session_time_max_milliseconds",
  otel_name: "browserless.session.time.max",
  unit: "ms",
  instrument: "gauge",
} as const;
/** Mean session time in milliseconds */
export const METRIC_BROWSERLESS_SESSION_TIME_MEAN = {
  name: "browserless_session_time_mean_milliseconds",
  otel_name: "browserless.session.time.mean",
  unit: "ms",
  instrument: "gauge",
} as const;
/** Minimum session time in milliseconds */
export const METRIC_BROWSERLESS_SESSION_TIME_MIN = {
  name: "browserless_session_time_min_milliseconds",
  otel_name: "browserless.session.time.min",
  unit: "ms",
  instrument: "gauge",
} as const;
/** Error sessions counter */
export const METRIC_BROWSERLESS_SESSIONS_ERROR = {
  name: "browserless_sessions_error_total",
  otel_name: "browserless.sessions.error",
  unit: "{session}",
  instrument: "counter",
} as const;
/** Currently queued sessions gauge */
export const METRIC_BROWSERLESS_SESSIONS_QUEUED = {
  name: "browserless_sessions_queued",
  otel_name: "browserless.sessions.queued",
  unit: "{session}",
  instrument: "gauge",
} as const;
/** Active sessions gauge */
export const METRIC_BROWSERLESS_SESSIONS_REGISTERED = {
  name: "browserless_sessions_registered",
  otel_name: "browserless.sessions.registered",
  unit: "{session}",
  instrument: "gauge",
} as const;
/** Total rejected sessions counter */
export const METRIC_BROWSERLESS_SESSIONS_REJECTED = {
  name: "browserless_sessions_rejected_total",
  otel_name: "browserless.sessions.rejected",
  unit: "{session}",
  instrument: "counter",
} as const;
/** Recently rejected sessions gauge */
export const METRIC_BROWSERLESS_SESSIONS_REJECTED_RECENT = {
  name: "browserless_sessions_rejected_recent",
  otel_name: "browserless.sessions.rejected.recent",
  unit: "{session}",
  instrument: "gauge",
} as const;
/** Currently running sessions gauge */
export const METRIC_BROWSERLESS_SESSIONS_RUNNING = {
  name: "browserless_sessions_running",
  otel_name: "browserless.sessions.running",
  unit: "{session}",
  instrument: "gauge",
} as const;
/** Successful sessions counter */
export const METRIC_BROWSERLESS_SESSIONS_SUCCESSFUL = {
  name: "browserless_sessions_successful_total",
  otel_name: "browserless.sessions.successful",
  unit: "{session}",
  instrument: "counter",
} as const;
/** Timed out sessions counter */
export const METRIC_BROWSERLESS_SESSIONS_TIMEDOUT = {
  name: "browserless_sessions_timedout_total",
  otel_name: "browserless.sessions.timedout",
  unit: "{session}",
  instrument: "counter",
} as const;
/** Total unhealthy sessions counter */
export const METRIC_BROWSERLESS_SESSIONS_UNHEALTHY = {
  name: "browserless_sessions_unhealthy_total",
  otel_name: "browserless.sessions.unhealthy",
  unit: "{session}",
  instrument: "counter",
} as const;
/** Socket state breakdown gauge */
export const METRIC_BROWSERLESS_SOCKET_STATE = {
  name: "browserless_socket_state",
  otel_name: "browserless.socket.state",
  unit: "{socket}",
  instrument: "gauge",
} as const;
/** Tab duration histogram */
export const METRIC_BROWSERLESS_TAB_DURATION = {
  name: "browserless_tab_duration_seconds",
  otel_name: "browserless.tab.duration",
  unit: "s",
  instrument: "histogram",
} as const;
/** Currently open tabs gauge */
export const METRIC_BROWSERLESS_TABS_OPEN = {
  name: "browserless_tabs_open",
  otel_name: "browserless.tabs.open",
  unit: "{tab}",
  instrument: "gauge",
} as const;
/** Total billing units counter */
export const METRIC_BROWSERLESS_UNITS = {
  name: "browserless_units_total",
  otel_name: "browserless.units",
  unit: "{unit}",
  instrument: "counter",
} as const;
/** WebSocket lifecycle events counter */
export const METRIC_BROWSERLESS_WS_LIFECYCLE = {
  name: "browserless_ws_lifecycle_total",
  otel_name: "browserless.ws.lifecycle",
  unit: "{event}",
  instrument: "counter",
} as const;
/** WS scope budget exceeded counter */
export const METRIC_BROWSERLESS_WS_SCOPE_BUDGET_EXCEEDED = {
  name: "browserless_ws_scope_budget_exceeded_total",
  otel_name: "browserless.ws.scope.budget.exceeded",
  unit: "{event}",
  instrument: "counter",
} as const;
/** Event loop lag 50th percentile */
export const METRIC_NODEJS_EVENTLOOP_LAG_P50 = {
  name: "nodejs_eventloop_lag_p50_seconds",
  otel_name: "nodejs.eventloop.lag.p50",
  unit: "s",
  instrument: "gauge",
} as const;
/** Event loop lag 99th percentile */
export const METRIC_NODEJS_EVENTLOOP_LAG_P99 = {
  name: "nodejs_eventloop_lag_p99_seconds",
  otel_name: "nodejs.eventloop.lag.p99",
  unit: "s",
  instrument: "gauge",
} as const;
/** Process system CPU seconds counter */
export const METRIC_PROCESS_CPU_SYSTEM = {
  name: "process_cpu_system_seconds_total",
  otel_name: "process.cpu.system",
  unit: "s",
  instrument: "counter",
} as const;
/** Process user CPU seconds counter */
export const METRIC_PROCESS_CPU_USER = {
  name: "process_cpu_user_seconds_total",
  otel_name: "process.cpu.user",
  unit: "s",
  instrument: "counter",
} as const;
/** Process external memory (C++ objects) */
export const METRIC_PROCESS_EXTERNAL = {
  name: "process_external_bytes",
  otel_name: "process.external",
  unit: "By",
  instrument: "gauge",
} as const;
/** V8 heap total bytes */
export const METRIC_PROCESS_HEAP_TOTAL = {
  name: "process_heap_total_bytes",
  otel_name: "process.heap.total",
  unit: "By",
  instrument: "gauge",
} as const;
/** V8 heap used bytes */
export const METRIC_PROCESS_HEAP_USED = {
  name: "process_heap_used_bytes",
  otel_name: "process.heap.used",
  unit: "By",
  instrument: "gauge",
} as const;
/** Process resident set size */
export const METRIC_PROCESS_RSS = {
  name: "process_rss_bytes",
  otel_name: "process.rss",
  unit: "By",
  instrument: "gauge",
} as const;
